[build]
builder = "nixpacks"
watchPatterns = ["cmd/pinger/**", "pkg", "migrations", "railway", "go.mod", "go.sum"]
buildCommand = "go build -o bin/pinger ./cmd/pinger"

[deploy]
startCommand = "bin/pinger"
cronSchedule = "0 8,19 * * *"
